name: Mirror to Local GitLab

on:
  push:
    branches: [ "**" ]

jobs:
  mirror:
    runs-on: [self-hosted, smm-runner01]
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config for push
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "mirror-bot@tk.local"

      - name: Mirror to Local GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          GITLAB_PROJECT_PATH="birfatura/smm.git"
          GITLAB_URL="http://tk-gitlab01-br1.tk.local/${GITLAB_PROJECT_PATH}"
          REMOTE_NAME="gitlab"

          if git remote | grep -q "^${REMOTE_NAME}$"; then
            git remote set-url ${REMOTE_NAME} "http://oauth2:${GITLAB_TOKEN}@tk-gitlab01-br1.tk.local/${GITLAB_PROJECT_PATH}"
          else
            git remote add ${REMOTE_NAME} "http://oauth2:${GITLAB_TOKEN}@tk-gitlab01-br1.tk.local/${GITLAB_PROJECT_PATH}"
          fi

          git push ${REMOTE_NAME} --all
          git push ${REMOTE_NAME} --tags

          for branch in $(git ls-remote --heads ${REMOTE_NAME} | awk '{print $2}' | sed 's|refs/heads/||'); do
            if ! git show-ref --verify --quiet refs/heads/$branch; then
              echo "Deleting remote branch: $branch"
              git push ${REMOTE_NAME} --delete $branch
            fi
          done
