jobs:
  mirror:
    runs-on: [self-hosted, smm-runner01]
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config for push
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "mirror-bot@tk.local"

      - name: Mirror to Local GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          GITLAB_PROJECT_PATH="birfatura/smm.git"   # Change if your namespace is different
          GITLAB_URL="http://tk-gitlab01-br1.tk.local/${GITLAB_PROJECT_PATH}"
          REMOTE_NAME="gitlab"

          # Check if remote exists; if yes, set-url, else add
          if git remote | grep -q "^${REMOTE_NAME}$"; then
            git remote set-url ${REMOTE_NAME} "http://oauth2:${GITLAB_TOKEN}@tk-gitlab01-br1.tk.local/${GITLAB_PROJECT_PATH}"
          else
            git remote add ${REMOTE_NAME} "http://oauth2:${GITLAB_TOKEN}@tk-gitlab01-br1.tk.local/${GITLAB_PROJECT_PATH}"
          fi

          git push --mirror ${REMOTE_NAME}
