name: Mirror to Local GitLab

on:
  push:
    branches: [ "**" ]   # Mirror all branches
  # optionally: add schedule, workflow_dispatch etc.

jobs:
  mirror:
    runs-on: [self-hosted, smm-runner01] # ensure your runner is picked
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch all history/branches

      - name: Set up Git config for push
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "mirror-bot@tk.local"

      - name: Mirror to Local GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # The repository path in GitLab
          GITLAB_PROJECT_PATH="birfatura/smm.git"   # <namespace>/<repo>.git; change 'root' if needed!
          GITLAB_URL="https://tk-gitlab01-br1.tk.local/${GITLAB_PROJECT_PATH}"
          # Add GitLab remote using the token
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@tk-gitlab01-br1.tk.local/${GITLAB_PROJECT_PATH}"
          # Push all refs (branches, tags)
          git push --mirror gitlab
